version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=hunsooooo.duckdns.org
      - VALIDATION=http
      # - SUBDOMAINS=www, #optional
      #- CERTPROVIDER= #optional
      - DNSPLUGIN=cloudflare #optional
      #- PROPAGATION= #optional
      - EMAIL=christian.plotzky@uniklinik-freiburg.de #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
