name: Docker Compose Actions Workflow
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: Linux
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker Containers
        run: sudo docker compose up -d --build

