name: Docker Compose Actions Workflow
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: Linux
    steps:
      - name: 'Cleanup build folder'
        run: sudo rm -rf CV
      - uses: actions/checkout@v2 
      - name: Build the Docker Containers
        run: cd CV && sudo docker-compose up -d --build
