name: Move html files workflow
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: Linux
    steps:
      - uses: actions/checkout@v3 
      - name: 'remove old files'
        run: sudo rm -rf /var/www/html/CV
      - name: 'move html files'
        run: sudo cp -r ~/actions-runner/_work/CV/CV /var/www/html
