name: Docker Compose Actions Workflow
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: Linux
    steps:
      - uses: actions/checkout@v3
      - name: copy html css
        run: cp -r html/* /home/topi/CV/html

